arp.o: arp.c /usr/include/stdc-predef.h ../include/arp.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/eth.h \
 ../include/pci.h ../include/locks.h ../include/net.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/lib/sys/select.h \
 ../include/lib/sys/time.h ../include/lib/os/if.h \
 ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/net.h \
 ../include/debug.h ../include/irq.h ../include/lib/sys/types.h \
 ../include/apic.h ../include/kprintf.h ../include/vga.h \
 ../include/multiboot.h ../include/console.h ../include/locks.h \
 ../include/lib/stdint.h ../include/lib/arpa/inet.h ../include/mm.h \
 ../include/tests.h ../include/pagetables.h ../include/lib/os/syscalls.h \
 ../include/net_if.h ../include/lib/string.h ../include/lib/unistd.h \
 ../include/lib/sys/types.h ../include/lib/getopt.h \
 ../include/lib/os/errors.h ../include/timer.h ../include/lib/sys/time.h \
 ../include/wq.h
blockcache.o: blockcache.c /usr/include/stdc-predef.h \
 ../include/blockcache.h ../include/ktypes.h ../include/lib/os/types.h \
 ../include/lib/unistd.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/lib/getopt.h ../include/dm.h \
 ../include/drivers.h ../include/kerrno.h ../include/lib/os/errors.h \
 ../include/drivers.h ../include/debug.h ../include/irq.h \
 ../include/lib/sys/types.h ../include/pci.h ../include/apic.h \
 ../include/kprintf.h ../include/vga.h ../include/multiboot.h \
 ../include/locks.h ../include/console.h ../include/lib/string.h \
 ../include/lib/unistd.h ../include/mm.h ../include/tests.h \
 ../include/pagetables.h ../include/kerrno.h
debug.o: debug.c /usr/include/stdc-predef.h ../include/debug.h \
 ../include/irq.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/pci.h ../include/ktypes.h \
 ../include/lib/os/types.h ../include/apic.h ../include/kprintf.h \
 ../include/vga.h ../include/multiboot.h ../include/locks.h \
 ../include/console.h ../include/gdt.h ../include/gdt_const.h \
 ../include/keyboard.h ../include/lib/termios.h \
 ../include/lib/sys/types.h ../include/lib/string.h \
 ../include/lib/unistd.h ../include/lib/getopt.h ../include/lib/stdlib.h \
 ../include/lib/stddef.h ../include/util.h ../include/mm.h \
 ../include/tests.h ../include/pagetables.h ../include/pm.h \
 ../include/lib/pthread.h ../include/lib/os/signals.h \
 ../include/lib/os/types.h ../include/lib/os/times.h \
 ../include/lib/sys/resource.h ../include/pagetables.h ../include/sched.h \
 ../include/pit.h ../include/reboot.h ../include/pci.h ../include/pata.h \
 ../include/drivers.h ../include/lib/unistd.h ../include/kerrno.h \
 ../include/lib/os/errors.h ../include/hd.h ../include/pm.h \
 ../include/mm.h ../include/ata.h ../include/irq.h ../include/ahci.h \
 ../include/fs.h ../include/lib/os/stat.h ../include/fs_pipe.h \
 ../include/lib/limits.h ../include/net.h ../include/eth.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/lib/netinet/in.h \
 ../include/lib/utime.h ../include/vga.h ../include/rtc.h \
 ../include/cpu.h ../include/smp.h ../include/smp_const.h \
 ../include/apic.h ../include/timer.h ../include/lib/sys/time.h \
 ../include/eth.h ../include/net_if.h ../include/ip.h \
 ../include/lib/os/route.h ../include/lib/os/if.h
dm.o: dm.c /usr/include/stdc-predef.h ../include/dm.h \
 ../include/drivers.h ../include/ktypes.h ../include/lib/os/types.h \
 ../include/lib/unistd.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/lib/getopt.h \
 ../include/kerrno.h ../include/lib/os/errors.h ../include/kerrno.h \
 ../include/debug.h ../include/irq.h ../include/lib/sys/types.h \
 ../include/pci.h ../include/apic.h ../include/kprintf.h ../include/vga.h \
 ../include/multiboot.h ../include/locks.h ../include/console.h \
 ../include/tty.h ../include/lib/termios.h ../include/pci.h \
 ../include/ramdisk.h ../include/pata.h ../include/hd.h ../include/pm.h \
 ../include/lib/pthread.h ../include/lib/os/signals.h \
 ../include/lib/os/types.h ../include/lib/os/times.h \
 ../include/lib/sys/resource.h ../include/mm.h ../include/tests.h \
 ../include/pagetables.h ../include/ata.h ../include/ahci.h \
 ../include/rtc.h ../include/8139.h ../include/eth.h
elf.o: elf.c /usr/include/stdc-predef.h ../include/elf.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/fs.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/lib/unistd.h ../include/lib/sys/types.h \
 ../include/lib/getopt.h ../include/lib/os/stat.h \
 ../include/lib/os/types.h ../include/lib/termios.h ../include/locks.h \
 ../include/pm.h ../include/lib/pthread.h ../include/irq.h \
 ../include/pci.h ../include/apic.h ../include/lib/os/signals.h \
 ../include/lib/os/times.h ../include/lib/sys/resource.h \
 ../include/fs_pipe.h ../include/lib/limits.h ../include/net.h \
 ../include/eth.h ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/lib/netinet/in.h \
 ../include/lib/utime.h ../include/kerrno.h ../include/lib/os/errors.h \
 ../include/mm.h ../include/tests.h ../include/pagetables.h \
 ../include/multiboot.h ../include/debug.h ../include/kprintf.h \
 ../include/vga.h ../include/console.h
fs.o: fs.c /usr/include/stdc-predef.h ../include/fs.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/lib/unistd.h ../include/lib/sys/types.h \
 ../include/lib/getopt.h ../include/lib/os/stat.h \
 ../include/lib/os/types.h ../include/lib/termios.h ../include/locks.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/pm.h \
 ../include/lib/pthread.h ../include/irq.h ../include/pci.h \
 ../include/apic.h ../include/lib/os/signals.h ../include/lib/os/times.h \
 ../include/lib/sys/resource.h ../include/fs_pipe.h \
 ../include/lib/limits.h ../include/net.h ../include/eth.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/lib/netinet/in.h \
 ../include/lib/utime.h ../include/fs_fat16.h ../include/fs.h \
 ../include/fs_ext2.h ../include/kerrno.h ../include/lib/os/errors.h \
 ../include/debug.h ../include/kprintf.h ../include/vga.h \
 ../include/multiboot.h ../include/console.h ../include/lib/string.h \
 ../include/lib/unistd.h ../include/lib/sys/stat.h ../include/mm.h \
 ../include/tests.h ../include/pagetables.h ../include/pm.h \
 ../include/lists.h ../include/locks.h ../include/dm.h \
 ../include/drivers.h ../include/kerrno.h ../include/drivers.h \
 ../include/blockcache.h ../include/lib/fcntl.h ../include/lib/os/stat.h \
 ../include/tty.h ../include/lib/stdint.h ../include/lib/termios.h \
 ../include/net.h ../include/lib/sys/select.h ../include/lib/limits.h \
 ../include/timer.h ../include/lib/sys/time.h ../include/util.h
fs_ext2.o: fs_ext2.c /usr/include/stdc-predef.h ../include/fs.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/lib/unistd.h ../include/lib/sys/types.h \
 ../include/lib/getopt.h ../include/lib/os/stat.h \
 ../include/lib/os/types.h ../include/lib/termios.h ../include/locks.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/pm.h \
 ../include/lib/pthread.h ../include/irq.h ../include/pci.h \
 ../include/apic.h ../include/lib/os/signals.h ../include/lib/os/times.h \
 ../include/lib/sys/resource.h ../include/fs_pipe.h \
 ../include/lib/limits.h ../include/net.h ../include/eth.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/lib/netinet/in.h \
 ../include/lib/utime.h ../include/fs_ext2.h ../include/fs.h \
 ../include/blockcache.h ../include/kerrno.h ../include/lib/os/errors.h \
 ../include/debug.h ../include/kprintf.h ../include/vga.h \
 ../include/multiboot.h ../include/console.h ../include/mm.h \
 ../include/tests.h ../include/pagetables.h ../include/drivers.h \
 ../include/kerrno.h ../include/lib/string.h ../include/lib/unistd.h \
 ../include/lists.h ../include/dm.h ../include/drivers.h ../include/pm.h \
 ../include/lib/time.h ../include/timer.h ../include/lib/sys/time.h \
 ../include/lib/sys/stat.h ../include/lib/utime.h
fs_fat16.o: fs_fat16.c /usr/include/stdc-predef.h ../include/fs.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/lib/unistd.h ../include/lib/sys/types.h \
 ../include/lib/getopt.h ../include/lib/os/stat.h \
 ../include/lib/os/types.h ../include/lib/termios.h ../include/locks.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/pm.h \
 ../include/lib/pthread.h ../include/irq.h ../include/pci.h \
 ../include/apic.h ../include/lib/os/signals.h ../include/lib/os/times.h \
 ../include/lib/sys/resource.h ../include/fs_pipe.h \
 ../include/lib/limits.h ../include/net.h ../include/eth.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/lib/netinet/in.h \
 ../include/lib/utime.h ../include/fs_fat16.h ../include/fs.h
fs_pipe.o: fs_pipe.c /usr/include/stdc-predef.h ../include/fs.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/lib/unistd.h ../include/lib/sys/types.h \
 ../include/lib/getopt.h ../include/lib/os/stat.h \
 ../include/lib/os/types.h ../include/lib/termios.h ../include/locks.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/pm.h \
 ../include/lib/pthread.h ../include/irq.h ../include/pci.h \
 ../include/apic.h ../include/lib/os/signals.h ../include/lib/os/times.h \
 ../include/lib/sys/resource.h ../include/fs_pipe.h \
 ../include/lib/limits.h ../include/net.h ../include/eth.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/lib/netinet/in.h \
 ../include/lib/utime.h ../include/fs_pipe.h ../include/kerrno.h \
 ../include/lib/os/errors.h ../include/debug.h ../include/kprintf.h \
 ../include/vga.h ../include/multiboot.h ../include/console.h \
 ../include/mm.h ../include/tests.h ../include/pagetables.h \
 ../include/pm.h ../include/util.h ../include/lib/string.h \
 ../include/lib/unistd.h
icmp.o: icmp.c /usr/include/stdc-predef.h ../include/net.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/locks.h \
 ../include/pci.h ../include/eth.h ../include/lib/sys/socket.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/ip.h \
 ../include/lib/os/route.h ../include/lib/os/if.h ../include/icmp.h \
 ../include/net.h ../include/debug.h ../include/irq.h \
 ../include/lib/sys/types.h ../include/apic.h ../include/kprintf.h \
 ../include/vga.h ../include/multiboot.h ../include/console.h \
 ../include/eth.h ../include/lib/string.h ../include/lib/unistd.h \
 ../include/lib/sys/types.h ../include/lib/getopt.h \
 ../include/lib/stdint.h ../include/lib/arpa/inet.h ../include/util.h
ip.o: ip.c /usr/include/stdc-predef.h ../include/net.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/locks.h \
 ../include/pci.h ../include/eth.h ../include/lib/sys/socket.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/ip.h \
 ../include/lib/os/route.h ../include/lib/os/if.h ../include/icmp.h \
 ../include/net.h ../include/debug.h ../include/irq.h \
 ../include/lib/sys/types.h ../include/apic.h ../include/kprintf.h \
 ../include/vga.h ../include/multiboot.h ../include/console.h \
 ../include/lib/stdint.h ../include/lib/arpa/inet.h \
 ../include/lib/netinet/in.h ../include/lib/os/errors.h \
 ../include/net_if.h ../include/params.h ../include/arp.h \
 ../include/lib/string.h ../include/lib/unistd.h \
 ../include/lib/sys/types.h ../include/lib/getopt.h ../include/wq.h \
 ../include/tcp.h ../include/udp.h ../include/util.h ../include/lists.h \
 ../include/mm.h ../include/tests.h ../include/pagetables.h \
 ../include/lib/os/route.h ../include/lib/os/if.h ../include/lib/stddef.h
irq.o: irq.c /usr/include/stdc-predef.h ../include/irq.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/pci.h ../include/ktypes.h ../include/lib/os/types.h \
 ../include/apic.h ../include/debug.h ../include/irq.h \
 ../include/kprintf.h ../include/vga.h ../include/multiboot.h \
 ../include/locks.h ../include/console.h ../include/pic.h \
 ../include/tests.h ../include/keyboard.h ../include/lib/termios.h \
 ../include/lib/sys/types.h ../include/io.h ../include/systemcalls.h \
 ../include/pm.h ../include/lib/pthread.h ../include/lib/os/signals.h \
 ../include/lib/os/types.h ../include/lib/os/times.h \
 ../include/lib/sys/resource.h ../include/sched.h ../include/pit.h \
 ../include/util.h ../include/kerrno.h ../include/lib/os/errors.h \
 ../include/pit.h ../include/pci.h ../include/mm.h ../include/tests.h \
 ../include/pagetables.h ../include/lists.h ../include/lib/string.h \
 ../include/lib/unistd.h ../include/lib/getopt.h ../include/params.h \
 ../include/cpu.h ../include/smp.h ../include/smp_const.h \
 ../include/gdt_const.h
kprintf.o: kprintf.c /usr/include/stdc-predef.h ../include/ktypes.h \
 ../include/lib/os/types.h ../include/vga.h ../include/multiboot.h \
 ../include/ktypes.h ../include/locks.h ../include/console.h \
 ../include/vga.h ../include/lib/stdarg.h ../include/kprintf.h
locks.o: locks.c /usr/include/stdc-predef.h ../include/locks.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/util.h \
 ../include/smp.h ../include/smp_const.h ../include/pm.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/locks.h ../include/lib/pthread.h ../include/irq.h \
 ../include/pci.h ../include/apic.h ../include/lib/os/signals.h \
 ../include/lib/os/types.h ../include/lib/os/times.h \
 ../include/lib/sys/resource.h ../include/debug.h ../include/kprintf.h \
 ../include/vga.h ../include/multiboot.h ../include/console.h
main.o: main.c /usr/include/stdc-predef.h ../include/debug.h \
 ../include/irq.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/pci.h ../include/ktypes.h \
 ../include/lib/os/types.h ../include/apic.h ../include/kprintf.h \
 ../include/vga.h ../include/multiboot.h ../include/locks.h \
 ../include/console.h ../include/vga.h ../include/console.h \
 ../include/util.h ../include/pic.h ../include/mm.h ../include/tests.h \
 ../include/pagetables.h ../include/keyboard.h ../include/lib/termios.h \
 ../include/lib/sys/types.h ../include/pm.h ../include/lib/pthread.h \
 ../include/lib/os/signals.h ../include/lib/os/types.h \
 ../include/lib/os/times.h ../include/lib/sys/resource.h \
 ../include/lib/unistd.h ../include/lib/getopt.h ../include/sched.h \
 ../include/pit.h ../include/lib/stdlib.h ../include/lib/unistd.h \
 ../include/lib/stddef.h ../include/lib/string.h ../include/params.h \
 ../include/dm.h ../include/drivers.h ../include/lib/unistd.h \
 ../include/kerrno.h ../include/lib/os/errors.h ../include/fs.h \
 ../include/lib/os/stat.h ../include/pm.h ../include/fs_pipe.h \
 ../include/lib/limits.h ../include/net.h ../include/eth.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/lib/netinet/in.h \
 ../include/lib/utime.h ../include/pit.h ../include/blockcache.h \
 ../include/pata.h ../include/hd.h ../include/mm.h ../include/ata.h \
 ../include/drivers.h ../include/ahci.h ../include/lib/os/oscalls.h \
 ../include/lib/os/signals.h ../include/lib/os/dirstreams.h \
 ../include/lib/sys/stat.h ../include/lib/sys/times.h \
 ../include/lib/sys/resource.h ../include/lib/termios.h \
 ../include/lib/sys/socket.h ../include/lib/utime.h \
 ../include/lib/os/syscalls.h ../include/smp.h ../include/smp_const.h \
 ../include/timer.h ../include/lib/sys/time.h ../include/cpu.h \
 ../include/sysmon.h ../include/arp.h ../include/net.h ../include/wq.h \
 ../include/tests.h
mm.o: mm.c /usr/include/stdc-predef.h ../include/mm.h ../include/ktypes.h \
 ../include/lib/os/types.h ../include/irq.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/pci.h ../include/apic.h \
 ../include/tests.h ../include/pagetables.h ../include/locks.h \
 ../include/multiboot.h ../include/lib/string.h ../include/lib/unistd.h \
 ../include/lib/sys/types.h ../include/lib/getopt.h ../include/debug.h \
 ../include/kprintf.h ../include/vga.h ../include/console.h \
 ../include/lists.h ../include/locks.h ../include/pagetables.h \
 ../include/util.h ../include/gdt.h ../include/gdt_const.h \
 ../include/lib/os/heap.h ../include/lib/os/types.h ../include/pm.h \
 ../include/lib/pthread.h ../include/lib/os/signals.h \
 ../include/lib/os/times.h ../include/lib/sys/resource.h \
 ../include/params.h ../include/kerrno.h ../include/lib/os/errors.h \
 ../include/smp.h ../include/smp_const.h
net.o: net.c /usr/include/stdc-predef.h ../include/net.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/locks.h \
 ../include/pci.h ../include/eth.h ../include/lib/sys/socket.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/mm.h \
 ../include/irq.h ../include/lib/sys/types.h ../include/apic.h \
 ../include/tests.h ../include/pagetables.h ../include/multiboot.h \
 ../include/pm.h ../include/lib/pthread.h ../include/lib/os/signals.h \
 ../include/lib/os/types.h ../include/lib/os/times.h \
 ../include/lib/sys/resource.h ../include/lib/string.h \
 ../include/lib/unistd.h ../include/lib/sys/types.h \
 ../include/lib/getopt.h ../include/debug.h ../include/kprintf.h \
 ../include/vga.h ../include/console.h ../include/lib/stdlib.h \
 ../include/lib/stddef.h ../include/lib/stdint.h \
 ../include/lib/arpa/inet.h ../include/lib/netinet/in.h ../include/arp.h \
 ../include/net.h ../include/util.h ../include/net_if.h \
 ../include/params.h ../include/ip.h ../include/lib/os/route.h \
 ../include/lib/os/if.h ../include/locks.h ../include/lib/os/errors.h \
 ../include/tcp.h ../include/udp.h ../include/lib/os/signals.h \
 ../include/lists.h ../include/lib/sys/ioctl.h ../include/timer.h \
 ../include/lib/sys/time.h
net_if.o: net_if.c /usr/include/stdc-predef.h ../include/eth.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/pci.h \
 ../include/locks.h ../include/net_if.h ../include/net.h ../include/eth.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/lib/sys/select.h \
 ../include/lib/sys/time.h ../include/lib/os/if.h \
 ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/arp.h \
 ../include/ip.h ../include/lib/os/route.h ../include/lib/os/if.h \
 ../include/lib/stdint.h ../include/lib/arpa/inet.h ../include/debug.h \
 ../include/irq.h ../include/lib/sys/types.h ../include/apic.h \
 ../include/kprintf.h ../include/vga.h ../include/multiboot.h \
 ../include/console.h ../include/lib/os/errors.h ../include/net.h \
 ../include/locks.h ../include/lib/os/syscalls.h ../include/lib/string.h \
 ../include/lib/unistd.h ../include/lib/sys/types.h \
 ../include/lib/getopt.h ../include/params.h ../include/wq.h \
 ../include/util.h ../include/lib/sys/ioctl.h
params.o: params.c /usr/include/stdc-predef.h ../include/params.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/lib/string.h \
 ../include/lib/unistd.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/lib/getopt.h \
 ../include/lib/stdlib.h ../include/lib/stddef.h ../include/debug.h \
 ../include/irq.h ../include/lib/sys/types.h ../include/pci.h \
 ../include/apic.h ../include/kprintf.h ../include/vga.h \
 ../include/multiboot.h ../include/locks.h ../include/console.h
pm.o: pm.c /usr/include/stdc-predef.h ../include/pm.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/locks.h ../include/ktypes.h ../include/lib/os/types.h \
 ../include/lib/pthread.h ../include/irq.h ../include/pci.h \
 ../include/apic.h ../include/lib/os/signals.h ../include/lib/os/types.h \
 ../include/lib/os/times.h ../include/lib/sys/resource.h ../include/wq.h \
 ../include/util.h ../include/kprintf.h ../include/vga.h \
 ../include/multiboot.h ../include/console.h ../include/debug.h \
 ../include/kprintf.h ../include/mm.h ../include/tests.h \
 ../include/pagetables.h ../include/gdt.h ../include/gdt_const.h \
 ../include/lib/string.h ../include/lib/unistd.h \
 ../include/lib/sys/types.h ../include/lib/getopt.h ../include/locks.h \
 ../include/irq.h ../include/sched.h ../include/pit.h ../include/kerrno.h \
 ../include/lib/os/errors.h ../include/lists.h ../include/fs.h \
 ../include/lib/unistd.h ../include/lib/os/stat.h \
 ../include/lib/termios.h ../include/pm.h ../include/fs_pipe.h \
 ../include/lib/limits.h ../include/net.h ../include/eth.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/lib/netinet/in.h \
 ../include/lib/utime.h ../include/elf.h ../include/rtc.h \
 ../include/lib/os/syscalls.h ../include/lib/os/stat.h \
 ../include/lib/sys/stat.h ../include/lib/os/times.h \
 ../include/lib/sys/resource.h ../include/timer.h \
 ../include/lib/sys/time.h ../include/smp.h ../include/smp_const.h \
 ../include/drivers.h ../include/kerrno.h ../include/tty.h \
 ../include/drivers.h
sched.o: sched.c /usr/include/stdc-predef.h ../include/pm.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/locks.h ../include/ktypes.h ../include/lib/os/types.h \
 ../include/lib/pthread.h ../include/irq.h ../include/pci.h \
 ../include/apic.h ../include/lib/os/signals.h ../include/lib/os/types.h \
 ../include/lib/os/times.h ../include/lib/sys/resource.h \
 ../include/sched.h ../include/pit.h ../include/locks.h \
 ../include/lists.h ../include/debug.h ../include/kprintf.h \
 ../include/vga.h ../include/multiboot.h ../include/console.h \
 ../include/smp.h ../include/smp_const.h ../include/util.h \
 ../include/timer.h ../include/lib/sys/time.h ../include/cpu.h \
 ../include/params.h
sysmon.o: sysmon.c /usr/include/stdc-predef.h ../include/vga.h \
 ../include/multiboot.h ../include/ktypes.h ../include/lib/os/types.h \
 ../include/locks.h ../include/console.h ../include/vga.h \
 ../include/console.h ../include/kprintf.h ../include/smp.h \
 ../include/smp_const.h ../include/sched.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/pit.h ../include/cpu.h \
 ../include/mm.h ../include/irq.h ../include/pci.h ../include/apic.h \
 ../include/tests.h ../include/pagetables.h ../include/lib/time.h \
 ../include/lib/sys/types.h ../include/pm.h ../include/lib/pthread.h \
 ../include/lib/os/signals.h ../include/lib/os/types.h \
 ../include/lib/os/times.h ../include/lib/sys/resource.h \
 ../include/lib/os/syscalls.h ../include/timer.h \
 ../include/lib/sys/time.h ../include/ahci.h ../include/drivers.h \
 ../include/lib/unistd.h ../include/lib/getopt.h ../include/kerrno.h \
 ../include/lib/os/errors.h ../include/hd.h ../include/pm.h \
 ../include/ata.h ../include/pata.h ../include/mm.h ../include/net_if.h \
 ../include/net.h ../include/eth.h ../include/lib/sys/socket.h \
 ../include/lib/sys/types.h ../include/lib/sys/select.h \
 ../include/lib/sys/time.h ../include/lib/os/if.h \
 ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h
systemcalls.o: systemcalls.c /usr/include/stdc-predef.h \
 ../include/systemcalls.h ../include/irq.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/pci.h ../include/ktypes.h \
 ../include/lib/os/types.h ../include/apic.h ../include/pm.h \
 ../include/locks.h ../include/lib/pthread.h ../include/lib/os/signals.h \
 ../include/lib/os/types.h ../include/lib/os/times.h \
 ../include/lib/sys/resource.h ../include/mm.h ../include/tests.h \
 ../include/pagetables.h ../include/multiboot.h ../include/debug.h \
 ../include/kprintf.h ../include/vga.h ../include/console.h \
 ../include/util.h ../include/kerrno.h ../include/lib/os/errors.h \
 ../include/fs.h ../include/lib/unistd.h ../include/lib/sys/types.h \
 ../include/lib/getopt.h ../include/lib/os/stat.h \
 ../include/lib/termios.h ../include/pm.h ../include/fs_pipe.h \
 ../include/lib/limits.h ../include/net.h ../include/eth.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/lib/netinet/in.h \
 ../include/lib/utime.h ../include/timer.h ../include/lib/sys/time.h \
 ../include/lib/os/syscalls.h ../include/lib/sys/ioctl.h
tcp.o: tcp.c /usr/include/stdc-predef.h ../include/tcp.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/net.h \
 ../include/locks.h ../include/pci.h ../include/eth.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/lib/sys/select.h \
 ../include/lib/sys/time.h ../include/lib/os/if.h \
 ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/lib/os/errors.h \
 ../include/lib/netinet/in.h ../include/net.h ../include/ip.h \
 ../include/lib/os/route.h ../include/lib/os/if.h ../include/debug.h \
 ../include/irq.h ../include/lib/sys/types.h ../include/apic.h \
 ../include/kprintf.h ../include/vga.h ../include/multiboot.h \
 ../include/console.h ../include/timer.h ../include/lib/sys/time.h \
 ../include/lists.h ../include/util.h ../include/params.h \
 ../include/lib/stddef.h ../include/lib/string.h ../include/lib/unistd.h \
 ../include/lib/sys/types.h ../include/lib/getopt.h \
 ../include/lib/ctype.h ../include/mm.h ../include/tests.h \
 ../include/pagetables.h
tests.o: tests.c /usr/include/stdc-predef.h ../include/tests.h \
 ../include/params.h ../include/ktypes.h ../include/lib/os/types.h \
 ../include/drivers.h ../include/lib/unistd.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/lib/getopt.h \
 ../include/kerrno.h ../include/lib/os/errors.h ../include/dm.h \
 ../include/drivers.h ../include/fs.h ../include/lib/sys/types.h \
 ../include/lib/os/stat.h ../include/lib/os/types.h \
 ../include/lib/termios.h ../include/locks.h ../include/pm.h \
 ../include/lib/pthread.h ../include/irq.h ../include/pci.h \
 ../include/apic.h ../include/lib/os/signals.h ../include/lib/os/times.h \
 ../include/lib/sys/resource.h ../include/fs_pipe.h \
 ../include/lib/limits.h ../include/net.h ../include/eth.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/lib/netinet/in.h \
 ../include/lib/utime.h ../include/pm.h ../include/mm.h \
 ../include/tests.h ../include/pagetables.h ../include/multiboot.h \
 ../include/debug.h ../include/kprintf.h ../include/vga.h \
 ../include/console.h ../include/locks.h ../include/util.h \
 ../include/lib/string.h ../include/lib/unistd.h ../include/pata.h \
 ../include/hd.h ../include/mm.h ../include/ata.h ../include/ahci.h \
 ../include/pit.h ../include/sched.h ../include/pit.h \
 ../include/lib/os/syscalls.h ../include/lib/os/oscalls.h \
 ../include/lib/os/signals.h ../include/lib/os/dirstreams.h \
 ../include/lib/sys/stat.h ../include/lib/sys/times.h \
 ../include/lib/sys/resource.h ../include/lib/termios.h \
 ../include/lib/sys/socket.h ../include/lib/utime.h ../include/smp.h \
 ../include/smp_const.h ../include/rtc.h ../include/timer.h \
 ../include/lib/sys/time.h ../include/io.h ../include/eth.h \
 ../include/net_if.h ../include/ip.h ../include/lib/os/route.h \
 ../include/lib/os/if.h
timer.o: timer.c /usr/include/stdc-predef.h ../include/irq.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/pci.h ../include/ktypes.h ../include/lib/os/types.h \
 ../include/apic.h ../include/pit.h ../include/rtc.h ../include/timer.h \
 ../include/locks.h ../include/lib/sys/time.h ../include/debug.h \
 ../include/irq.h ../include/kprintf.h ../include/vga.h \
 ../include/multiboot.h ../include/console.h ../include/smp.h \
 ../include/smp_const.h ../include/sched.h ../include/pit.h \
 ../include/pm.h ../include/lib/pthread.h ../include/lib/os/signals.h \
 ../include/lib/os/types.h ../include/lib/os/times.h \
 ../include/lib/sys/resource.h ../include/util.h \
 ../include/lib/sys/time.h ../include/lib/limits.h ../include/lists.h \
 ../include/mm.h ../include/tests.h ../include/pagetables.h \
 ../include/locks.h ../include/keyboard.h ../include/lib/termios.h \
 ../include/lib/sys/types.h ../include/vga.h ../include/sysmon.h \
 ../include/tcp.h ../include/net.h ../include/eth.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/ip.h \
 ../include/lib/os/route.h ../include/lib/os/if.h ../include/lib/stddef.h
udp.o: udp.c /usr/include/stdc-predef.h ../include/net.h \
 ../include/ktypes.h ../include/lib/os/types.h ../include/locks.h \
 ../include/pci.h ../include/eth.h ../include/lib/sys/socket.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/udp.h \
 ../include/net.h ../include/mm.h ../include/irq.h \
 ../include/lib/sys/types.h ../include/apic.h ../include/tests.h \
 ../include/pagetables.h ../include/multiboot.h ../include/lib/string.h \
 ../include/lib/unistd.h ../include/lib/sys/types.h \
 ../include/lib/getopt.h ../include/lib/os/errors.h \
 ../include/lib/stddef.h ../include/lists.h ../include/ip.h \
 ../include/lib/os/route.h ../include/lib/os/if.h ../include/debug.h \
 ../include/kprintf.h ../include/vga.h ../include/console.h \
 ../include/util.h ../include/icmp.h
wq.o: wq.c /usr/include/stdc-predef.h ../include/wq.h ../include/ktypes.h \
 ../include/lib/os/types.h ../include/locks.h ../include/smp.h \
 ../include/smp_const.h ../include/lib/string.h ../include/lib/unistd.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/lib/getopt.h ../include/lib/os/errors.h \
 ../include/lib/pthread.h ../include/debug.h ../include/irq.h \
 ../include/lib/sys/types.h ../include/pci.h ../include/apic.h \
 ../include/kprintf.h ../include/vga.h ../include/multiboot.h \
 ../include/console.h ../include/timer.h ../include/lib/sys/time.h \
 ../include/lib/os/syscalls.h ../include/sched.h ../include/pit.h
