dirstreams.o: dirstreams.c /usr/include/stdc-predef.h \
 ../../include/lib/os/dirstreams.h ../../include/lib/os/types.h \
 ../../include/lib/os/errors.h ../../include/lib/stdlib.h \
 ../../include/lib/unistd.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h ../../include/lib/getopt.h \
 ../../include/lib/stddef.h ../../include/lib/errno.h \
 ../../include/lib/os/errors.h ../../include/lib/os/oscalls.h \
 ../../include/lib/os/signals.h ../../include/lib/os/dirstreams.h \
 ../../include/lib/sys/stat.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/times.h ../../include/lib/sys/resource.h \
 ../../include/lib/termios.h ../../include/lib/sys/socket.h \
 ../../include/lib/sys/select.h ../../include/lib/sys/time.h \
 ../../include/lib/utime.h
heap.o: heap.c /usr/include/stdc-predef.h ../../include/lib/os/heap.h \
 ../../include/lib/os/types.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h ../../include/debug.h \
 ../../include/irq.h ../../include/lib/sys/types.h ../../include/pci.h \
 ../../include/ktypes.h ../../include/lib/os/types.h ../../include/apic.h \
 ../../include/kprintf.h ../../include/vga.h ../../include/multiboot.h \
 ../../include/locks.h ../../include/console.h
math.o: math.c /usr/include/stdc-predef.h
pwddb.o: pwddb.c /usr/include/stdc-predef.h ../../include/lib/os/pwddb.h \
 ../../include/lib/os/types.h ../../include/lib/stdio.h \
 ../../include/lib/stddef.h ../../include/lib/os/streams.h \
 ../../include/lib/sys/types.h ../../include/lib/sys/../os/types.h \
 ../../include/lib/stdarg.h ../../include/lib/string.h \
 ../../include/lib/unistd.h ../../include/lib/getopt.h \
 ../../include/lib/stdlib.h ../../include/lib/os/errors.h
resolv.o: resolv.c /usr/include/stdc-predef.h ../../include/lib/stdio.h \
 ../../include/lib/stddef.h ../../include/lib/os/streams.h \
 ../../include/lib/os/types.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h ../../include/lib/stdarg.h \
 ../../include/lib/arpa/inet.h ../../include/lib/netinet/in.h \
 ../../include/lib/netinet/../sys/socket.h \
 ../../include/lib/netinet/../sys/types.h \
 ../../include/lib/netinet/../sys/select.h \
 ../../include/lib/netinet/../sys/time.h \
 ../../include/lib/netinet/../inttypes.h \
 ../../include/lib/netinet/../stdint.h \
 ../../include/lib/netinet/../arpa/inet.h ../../include/lib/unistd.h \
 ../../include/lib/getopt.h ../../include/lib/sys/socket.h \
 ../../include/lib/string.h ../../include/lib/unistd.h \
 ../../include/lib/os/resolv.h ../../include/lib/os/../netdb.h \
 ../../include/lib/stdlib.h ../../include/lib/errno.h \
 ../../include/lib/os/errors.h ../../include/lib/netdb.h \
 ../../include/lib/os/if.h ../../include/lib/os/../netinet/in.h \
 ../../include/lib/sys/ioctl.h
streams.o: streams.c /usr/include/stdc-predef.h \
 ../../include/lib/os/streams.h ../../include/lib/os/types.h \
 ../../include/lib/stdio.h ../../include/lib/stddef.h \
 ../../include/lib/os/streams.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h ../../include/lib/stdarg.h \
 ../../include/lib/stdlib.h ../../include/lib/unistd.h \
 ../../include/lib/getopt.h ../../include/lib/os/errors.h \
 ../../include/lib/os/oscalls.h ../../include/lib/os/signals.h \
 ../../include/lib/os/dirstreams.h ../../include/lib/sys/stat.h \
 ../../include/lib/sys/types.h ../../include/lib/sys/times.h \
 ../../include/lib/sys/resource.h ../../include/lib/termios.h \
 ../../include/lib/sys/socket.h ../../include/lib/sys/select.h \
 ../../include/lib/sys/time.h ../../include/lib/utime.h \
 ../../include/lists.h
