close.o: close.c /usr/include/stdc-predef.h \
 ../../include/lib/os/oscalls.h ../../include/lib/os/types.h \
 ../../include/lib/os/signals.h ../../include/lib/os/dirstreams.h \
 ../../include/lib/sys/stat.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h ../../include/lib/sys/times.h \
 ../../include/lib/sys/resource.h ../../include/lib/termios.h \
 ../../include/lib/sys/types.h ../../include/lib/sys/socket.h \
 ../../include/lib/sys/select.h ../../include/lib/sys/time.h \
 ../../include/lib/utime.h
crt0.o: crt0.c /usr/include/stdc-predef.h ../../include/lib/os/heap.h \
 ../../include/lib/os/types.h ../../include/lib/os/oscalls.h \
 ../../include/lib/os/signals.h ../../include/lib/os/dirstreams.h \
 ../../include/lib/sys/stat.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h ../../include/lib/sys/times.h \
 ../../include/lib/sys/resource.h ../../include/lib/termios.h \
 ../../include/lib/sys/types.h ../../include/lib/sys/socket.h \
 ../../include/lib/sys/select.h ../../include/lib/sys/time.h \
 ../../include/lib/utime.h ../../include/lib/stdio.h \
 ../../include/lib/stddef.h ../../include/lib/os/streams.h \
 ../../include/lib/stdarg.h ../../include/lib/unistd.h \
 ../../include/lib/getopt.h ../../include/lib/stdlib.h \
 ../../include/lib/unistd.h ../../include/lib/string.h
exec.o: exec.c /usr/include/stdc-predef.h
exit.o: exit.c /usr/include/stdc-predef.h
fork.o: fork.c /usr/include/stdc-predef.h
getdent.o: getdent.c /usr/include/stdc-predef.h \
 ../../include/lib/os/dirstreams.h ../../include/lib/os/types.h \
 ../../include/lib/os/syscalls.h
ioctl.o: ioctl.c /usr/include/stdc-predef.h ../../include/lib/sys/ioctl.h \
 ../../include/lib/os/oscalls.h ../../include/lib/os/types.h \
 ../../include/lib/os/signals.h ../../include/lib/os/dirstreams.h \
 ../../include/lib/sys/stat.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h ../../include/lib/sys/times.h \
 ../../include/lib/sys/resource.h ../../include/lib/termios.h \
 ../../include/lib/sys/types.h ../../include/lib/sys/socket.h \
 ../../include/lib/sys/select.h ../../include/lib/sys/time.h \
 ../../include/lib/utime.h
lseek.o: lseek.c /usr/include/stdc-predef.h \
 ../../include/lib/os/oscalls.h ../../include/lib/os/types.h \
 ../../include/lib/os/signals.h ../../include/lib/os/dirstreams.h \
 ../../include/lib/sys/stat.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h ../../include/lib/sys/times.h \
 ../../include/lib/sys/resource.h ../../include/lib/termios.h \
 ../../include/lib/sys/types.h ../../include/lib/sys/socket.h \
 ../../include/lib/sys/select.h ../../include/lib/sys/time.h \
 ../../include/lib/utime.h
open.o: open.c /usr/include/stdc-predef.h ../../include/lib/os/oscalls.h \
 ../../include/lib/os/types.h ../../include/lib/os/signals.h \
 ../../include/lib/os/dirstreams.h ../../include/lib/sys/stat.h \
 ../../include/lib/sys/types.h ../../include/lib/sys/../os/types.h \
 ../../include/lib/sys/times.h ../../include/lib/sys/resource.h \
 ../../include/lib/termios.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/socket.h ../../include/lib/sys/select.h \
 ../../include/lib/sys/time.h ../../include/lib/utime.h
read.o: read.c /usr/include/stdc-predef.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h
sbrk.o: sbrk.c /usr/include/stdc-predef.h ../../include/lib/os/oscalls.h \
 ../../include/lib/os/types.h ../../include/lib/os/signals.h \
 ../../include/lib/os/dirstreams.h ../../include/lib/sys/stat.h \
 ../../include/lib/sys/types.h ../../include/lib/sys/../os/types.h \
 ../../include/lib/sys/times.h ../../include/lib/sys/resource.h \
 ../../include/lib/termios.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/socket.h ../../include/lib/sys/select.h \
 ../../include/lib/sys/time.h ../../include/lib/utime.h
signals.o: signals.c /usr/include/stdc-predef.h \
 ../../include/lib/os/oscalls.h ../../include/lib/os/types.h \
 ../../include/lib/os/signals.h ../../include/lib/os/dirstreams.h \
 ../../include/lib/sys/stat.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h ../../include/lib/sys/times.h \
 ../../include/lib/sys/resource.h ../../include/lib/termios.h \
 ../../include/lib/sys/types.h ../../include/lib/sys/socket.h \
 ../../include/lib/sys/select.h ../../include/lib/sys/time.h \
 ../../include/lib/utime.h ../../include/lib/os/errors.h
sleep.o: sleep.c /usr/include/stdc-predef.h
stat.o: stat.c /usr/include/stdc-predef.h ../../include/lib/sys/stat.h \
 ../../include/lib/sys/types.h ../../include/lib/sys/../os/types.h \
 ../../include/lib/utime.h
unistd.o: unistd.c /usr/include/stdc-predef.h \
 ../../include/lib/os/oscalls.h ../../include/lib/os/types.h \
 ../../include/lib/os/signals.h ../../include/lib/os/dirstreams.h \
 ../../include/lib/sys/stat.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h ../../include/lib/sys/times.h \
 ../../include/lib/sys/resource.h ../../include/lib/termios.h \
 ../../include/lib/sys/types.h ../../include/lib/sys/socket.h \
 ../../include/lib/sys/select.h ../../include/lib/sys/time.h \
 ../../include/lib/utime.h
unlink.o: unlink.c /usr/include/stdc-predef.h \
 ../../include/lib/os/oscalls.h ../../include/lib/os/types.h \
 ../../include/lib/os/signals.h ../../include/lib/os/dirstreams.h \
 ../../include/lib/sys/stat.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h ../../include/lib/sys/times.h \
 ../../include/lib/sys/resource.h ../../include/lib/termios.h \
 ../../include/lib/sys/types.h ../../include/lib/sys/socket.h \
 ../../include/lib/sys/select.h ../../include/lib/sys/time.h \
 ../../include/lib/utime.h
wait.o: wait.c /usr/include/stdc-predef.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h
write.o: write.c /usr/include/stdc-predef.h ../../include/lib/sys/types.h \
 ../../include/lib/sys/../os/types.h
