cli.o: cli.c /usr/include/stdc-predef.h ../include/lib/unistd.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/lib/getopt.h ../include/lib/string.h ../include/lib/unistd.h \
 ../include/lib/stdlib.h ../include/lib/stddef.h ../include/lib/fcntl.h \
 ../include/lib/sys/stat.h ../include/lib/sys/types.h \
 ../include/lib/errno.h ../include/lib/os/errors.h ../include/lib/stdio.h \
 ../include/lib/os/streams.h ../include/lib/os/types.h \
 ../include/lib/stdarg.h ../include/lib/sys/wait.h \
 ../include/lib/sys/resource.h ../include/lib/signal.h \
 ../include/lib/os/signals.h ../include/lib/dirent.h \
 ../include/lib/os/dirstreams.h ../include/lib/sys/times.h \
 ../include/lib/assert.h ../include/lib/time.h \
 ../include/lib/sys/socket.h ../include/lib/sys/select.h \
 ../include/lib/sys/time.h ../include/lib/sys/ioctl.h \
 ../include/lib/os/if.h ../include/lib/os/../netinet/in.h \
 ../include/lib/os/../netinet/../sys/socket.h \
 ../include/lib/os/../netinet/../inttypes.h \
 ../include/lib/os/../netinet/../stdint.h \
 ../include/lib/os/../netinet/../arpa/inet.h ../include/lib/os/route.h \
 ../include/lib/os/if.h ../include/lib/netdb.h ../include/lib/pwd.h
host.o: host.c /usr/include/stdc-predef.h ../include/lib/stdio.h \
 ../include/lib/stddef.h ../include/lib/os/streams.h \
 ../include/lib/os/types.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/lib/stdarg.h \
 ../include/lib/sys/socket.h ../include/lib/sys/types.h \
 ../include/lib/sys/select.h ../include/lib/sys/time.h \
 ../include/lib/arpa/inet.h ../include/lib/netinet/in.h \
 ../include/lib/netinet/../sys/socket.h \
 ../include/lib/netinet/../inttypes.h ../include/lib/netinet/../stdint.h \
 ../include/lib/netinet/../arpa/inet.h ../include/lib/unistd.h \
 ../include/lib/getopt.h ../include/lib/os/resolv.h \
 ../include/lib/os/../netdb.h
init.o: init.c /usr/include/stdc-predef.h ../include/lib/unistd.h \
 ../include/lib/sys/types.h ../include/lib/sys/../os/types.h \
 ../include/lib/getopt.h ../include/lib/stdio.h ../include/lib/stddef.h \
 ../include/lib/os/streams.h ../include/lib/os/types.h \
 ../include/lib/stdarg.h ../include/lib/sys/wait.h \
 ../include/lib/sys/resource.h ../include/lib/errno.h \
 ../include/lib/os/errors.h
lc.o: lc.c /usr/include/stdc-predef.h ../include/lib/stdio.h \
 ../include/lib/stddef.h ../include/lib/os/streams.h \
 ../include/lib/os/types.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/lib/stdarg.h
loop.o: loop.c /usr/include/stdc-predef.h ../include/lib/stdio.h \
 ../include/lib/stddef.h ../include/lib/os/streams.h \
 ../include/lib/os/types.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/lib/stdarg.h \
 ../include/lib/stdlib.h ../include/lib/unistd.h ../include/lib/getopt.h
uname.o: uname.c /usr/include/stdc-predef.h ../include/lib/stdio.h \
 ../include/lib/stddef.h ../include/lib/os/streams.h \
 ../include/lib/os/types.h ../include/lib/sys/types.h \
 ../include/lib/sys/../os/types.h ../include/lib/stdarg.h \
 ../include/lib/unistd.h ../include/lib/getopt.h
